server:
  port: 9292
spring:
  application:
    name: SPRING_SECURITY_DB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sbsecurity
    username: root
    password: myadmin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true		